### PR TITLE
Added PDF-Shuffler & standby indicator timer to wishlist ; added ambient noise player to apps

### PR DESCRIPTION
**Pull request by orschiro**
However, ambient noise player does not show up in the apps list. I have no idea why.

### CODE REVIEW

**Comment by quassy** [comment]
Thanks a lot for your contribution! I'd like to merge the 1st and 3rd commit immediately but I got an issue with the 2nd as it is right now, but I don't know how to only pick certain commits.

**Comment by orschiro** [comment]
@quassy 

I actually didn't intend to bundle them. It just occurred automatically. Maybe merge all of them and modify the description manually?

**Comment by quassy** [comment]
I had the same problem (multiple commits in one PR) once too, apparently that's how GitHub works even though I find it weird. Yes I will do that when I find the time, thanks again for the contribution :)

**Comment by orschiro** [comment]
Welcome and happy Easter!

**Comment by quassy** [comment]
Now merged, including [Ambient Noise Player](http://quassy.github.io/elementary-apps/Ambient%20Noise%20Player/)

**Pull request merged**
